### ISSUE TITLE
expecting \"[Some('='), Some(':')]\" but found EOF

### ISSUE THREAD

**Issue by pikhovkin** [zonyitoo/rust-ini#123]
There is `rust-ini==0.20.0` and a `conf.ini`
```ini
; conf.ini
[Book]
path=path/a/b
name=Some name
list=
    444
    555
    666
```
I ran `main.rs`
```rust
use ini::Ini;

fn main() {
    let conf = Ini::load_from_file("./file.ini").unwrap();
    let section = conf.section(Some("Book")).unwrap();
    let path = section.get("path").unwrap();
    println!("{:?}: {:?}", section, path);
}

```
and got this err
```console
thread 'main' panicked at src/main.rs:4:50:
called `Result::unwrap()` on an `Err` value: Parse(ParseError { line: 9, col: 1, msg: "expecting \"[Some('='), Some(':')]\" but found EOF." })
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1649:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1073:23
   4: rs_pull_repos::main
             at ./src/main.rs:4:16
   5: core::ops::function::FnOnce::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

Process finished with exit code 101
```

**Comment by zonyitoo** [comment]
Multiline value is not supported by ini's standard.
